# Generated by Django 4.0 on 2021-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(default='', max_length=128, verbose_name='middle name')),
                ('last_name', models.CharField(default='', max_length=128, verbose_name='last name')),
                ('first_name', models.CharField(default='', max_length=512, verbose_name='full name')),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('register_date', models.DateTimeField(verbose_name='birth date')),
                ('years', models.IntegerField(default=0)),
            ],
        ),
    ]
