# Generated by Django 4.0 on 2021-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(default='', max_length=512, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='', max_length=128, verbose_name='first name'),
        ),
    ]
